/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import classes.FileManager;
import GUI.Principal;
import classes.ABB;
import classes.Lista;
import classes.User;
import classes.Room;
import classes.GuiLogic;
import classes.GuiLogic;
import java.awt.Color;
import javax.swing.JOptionPane;
import classes.TablaHash;
/**
 *
 * @author carre
 */
public class AdminActions extends javax.swing.JFrame {
    User[] a;
Room[] rooms;
Lista<User> roomsHistoric;
Lista<User> reservationsUsers;
ABB arbolito;
TablaHash tabla;
    
    GuiLogic guiLogic = new GuiLogic();
    String userInput;
    int numericInput;
    String iDInputExample = "ID | Example: 29100210";
    String registrationInputExample = "Name, Last name | Example: Luis Carreño";
    String historyInputExample = "Room number | Example: 12";
    
    
    /**
     * Creates new form AdminActions
     */
    public AdminActions(User[] a, Room[] rooms, Lista<User> roomsHistoric,  Lista<User> reservationsUsers, ABB arbolito, TablaHash tabla) {
        this.a=a;
        this.rooms=rooms;
        this.roomsHistoric=roomsHistoric;
        this.reservationsUsers=reservationsUsers;
        this.arbolito=arbolito;
        this.tabla=tabla;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkRButton = new javax.swing.JButton();
        searchRButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();
        historyInput = new javax.swing.JTextField();
        checkRInput = new javax.swing.JTextField();
        checkOutInput = new javax.swing.JTextField();
        searchRInput = new javax.swing.JTextField();
        checkInButton1 = new javax.swing.JButton();
        checkInInput1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkRButton.setBackground(new java.awt.Color(204, 204, 204));
        checkRButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkRButton.setForeground(new java.awt.Color(0, 0, 0));
        checkRButton.setText("Check Registration");
        checkRButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        checkRButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkRButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkRButtonMouseClicked(evt);
            }
        });
        checkRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRButtonActionPerformed(evt);
            }
        });
        jPanel1.add(checkRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 140, 50));

        searchRButton.setBackground(new java.awt.Color(204, 204, 204));
        searchRButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchRButton.setForeground(new java.awt.Color(0, 0, 0));
        searchRButton.setText("Search Reservation");
        searchRButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchRButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchRButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchRButtonMouseClicked(evt);
            }
        });
        searchRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 140, 50));

        historyButton.setBackground(new java.awt.Color(204, 204, 204));
        historyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        historyButton.setForeground(new java.awt.Color(0, 0, 0));
        historyButton.setText("Room History");
        historyButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        historyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyButtonMouseClicked(evt);
            }
        });
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(historyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 140, 50));

        checkOutButton.setBackground(new java.awt.Color(204, 204, 204));
        checkOutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkOutButton.setForeground(new java.awt.Color(0, 0, 0));
        checkOutButton.setText("Check Out");
        checkOutButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        checkOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutButtonMouseClicked(evt);
            }
        });
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(checkOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 140, 50));

        historyInput.setBackground(new java.awt.Color(255, 255, 223));
        historyInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        historyInput.setForeground(new java.awt.Color(153, 153, 153));
        historyInput.setText("Room number | Example: 12");
        historyInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyInputMouseClicked(evt);
            }
        });
        historyInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyInputActionPerformed(evt);
            }
        });
        jPanel1.add(historyInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 380, 30));

        checkRInput.setBackground(new java.awt.Color(255, 255, 223));
        checkRInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkRInput.setForeground(new java.awt.Color(153, 153, 153));
        checkRInput.setText("Name, Last name | Example: Luis Carreño");
        checkRInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkRInputMouseClicked(evt);
            }
        });
        checkRInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRInputActionPerformed(evt);
            }
        });
        jPanel1.add(checkRInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 380, 30));

        checkOutInput.setBackground(new java.awt.Color(255, 255, 223));
        checkOutInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkOutInput.setForeground(new java.awt.Color(153, 153, 153));
        checkOutInput.setText("ID | Example: 29100210");
        checkOutInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutInputMouseClicked(evt);
            }
        });
        checkOutInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutInputActionPerformed(evt);
            }
        });
        jPanel1.add(checkOutInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 380, 30));

        searchRInput.setBackground(new java.awt.Color(255, 255, 223));
        searchRInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchRInput.setForeground(new java.awt.Color(153, 153, 153));
        searchRInput.setText("ID | Example: 29100210");
        searchRInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchRInputMouseClicked(evt);
            }
        });
        searchRInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRInputActionPerformed(evt);
            }
        });
        jPanel1.add(searchRInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 380, 30));

        checkInButton1.setBackground(new java.awt.Color(204, 204, 204));
        checkInButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkInButton1.setForeground(new java.awt.Color(0, 0, 0));
        checkInButton1.setText("Check In");
        checkInButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        checkInButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkInButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkInButton1MouseClicked(evt);
            }
        });
        checkInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(checkInButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 140, 50));

        checkInInput1.setBackground(new java.awt.Color(255, 255, 223));
        checkInInput1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkInInput1.setForeground(new java.awt.Color(153, 153, 153));
        checkInInput1.setText("ID | Example: 29100210");
        checkInInput1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkInInput1MouseClicked(evt);
            }
        });
        checkInInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInInput1ActionPerformed(evt);
            }
        });
        jPanel1.add(checkInInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 380, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkRButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkRButtonMouseClicked

    }//GEN-LAST:event_checkRButtonMouseClicked

    private void checkRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRButtonActionPerformed
        userInput = checkRInput.getText();
        String auxUserInput = userInput.replace(" ", "");
        if (!userInput.contains(" ")) {
            JOptionPane.showMessageDialog(null, "Check registration input must be (name space last name).");
        } else if (auxUserInput.matches("[a-zA-Z]+")) {
            //matches
            guiLogic.function1(userInput, null);
        }
    }//GEN-LAST:event_checkRButtonActionPerformed

    private void searchRButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchRButtonMouseClicked

    }//GEN-LAST:event_searchRButtonMouseClicked

    private void searchRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRButtonActionPerformed
        userInput = searchRInput.getText();
        if (!userInput.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Search reservation must be only numbers");
        } else {
            //matches
            numericInput = Integer.parseInt(userInput);
            guiLogic.function2(numericInput, null);
        }
    }//GEN-LAST:event_searchRButtonActionPerformed

    private void historyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyButtonMouseClicked
        userInput = historyInput.getText();
        if (!userInput.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Room history must be only numbers");
        } else {
            //matches
            numericInput = Integer.parseInt(userInput);
            guiLogic.function3(numericInput, null);
        }
    }//GEN-LAST:event_historyButtonMouseClicked

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyButtonActionPerformed

    private void checkOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutButtonMouseClicked
        userInput = checkOutInput.getText();
        if (!userInput.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Check out must be only numbers");
        } else {
            //matches
            numericInput = Integer.parseInt(userInput);
            guiLogic.checkOut(numericInput, null, null);
        }
    }//GEN-LAST:event_checkOutButtonMouseClicked

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void historyInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyInputMouseClicked
        if (historyInputExample.equals(historyInput.getText())) {
            historyInput.setText("");
            historyInput.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_historyInputMouseClicked

    private void checkRInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkRInputMouseClicked
        if (registrationInputExample.equals(checkRInput.getText())) {
            checkRInput.setText("");
            checkRInput.setForeground(Color.black);
        }
    }//GEN-LAST:event_checkRInputMouseClicked

    private void checkRInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRInputActionPerformed
   
    }//GEN-LAST:event_checkRInputActionPerformed

    private void checkOutInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutInputMouseClicked
       if (iDInputExample.equals(checkOutInput.getText())) {
            checkOutInput.setText("");
            checkOutInput.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_checkOutInputMouseClicked

    private void checkOutInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutInputActionPerformed
        
    }//GEN-LAST:event_checkOutInputActionPerformed

    private void searchRInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchRInputMouseClicked
       if (iDInputExample.equals(searchRInput.getText())) {
            searchRInput.setText("");
            searchRInput.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchRInputMouseClicked

    private void searchRInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRInputActionPerformed
        
    }//GEN-LAST:event_searchRInputActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void historyInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyInputActionPerformed
       
    }//GEN-LAST:event_historyInputActionPerformed

    private void checkInButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInButton1MouseClicked
        userInput = checkInInput1.getText();
        if (!userInput.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Check in must be only numbers");
        } else {
            //matches
            numericInput = Integer.parseInt(userInput);
            guiLogic.checkIn(numericInput, null, null, null);
        }
    }//GEN-LAST:event_checkInButton1MouseClicked

    private void checkInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInButton1ActionPerformed

    private void checkInInput1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInInput1MouseClicked
        if (iDInputExample.equals(checkInInput1.getText())) {
            checkInInput1.setText("");
            checkInInput1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_checkInInput1MouseClicked

    private void checkInInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInInput1ActionPerformed

    }//GEN-LAST:event_checkInInput1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkInButton1;
    private javax.swing.JTextField checkInInput1;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JTextField checkOutInput;
    private javax.swing.JButton checkRButton;
    private javax.swing.JTextField checkRInput;
    private javax.swing.JButton historyButton;
    private javax.swing.JTextField historyInput;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchRButton;
    private javax.swing.JTextField searchRInput;
    // End of variables declaration//GEN-END:variables
}
