/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author carre
 */
public class AdminActions extends javax.swing.JFrame {

    /**
     * Creates new form AdminActions
     */
    public AdminActions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CheckRegistrationButton = new javax.swing.JButton();
        SearchReservationButton = new javax.swing.JButton();
        HistoryButton = new javax.swing.JButton();
        CheckOutButton = new javax.swing.JButton();
        backToGraphVisualizer = new javax.swing.JButton();
        deleteUserInput = new javax.swing.JTextField();
        addUserInput = new javax.swing.JTextField();
        deleteRelationInput = new javax.swing.JTextField();
        addRelationInput = new javax.swing.JTextField();
        CheckInButton = new javax.swing.JButton();
        deleteRelationInput1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CheckRegistrationButton.setBackground(new java.awt.Color(204, 204, 204));
        CheckRegistrationButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckRegistrationButton.setForeground(new java.awt.Color(0, 0, 0));
        CheckRegistrationButton.setText("Check Registration");
        CheckRegistrationButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CheckRegistrationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckRegistrationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckRegistrationButtonMouseClicked(evt);
            }
        });
        CheckRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckRegistrationButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CheckRegistrationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 140, 50));

        SearchReservationButton.setBackground(new java.awt.Color(204, 204, 204));
        SearchReservationButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchReservationButton.setForeground(new java.awt.Color(0, 0, 0));
        SearchReservationButton.setText("Search Reservation");
        SearchReservationButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SearchReservationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchReservationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchReservationButtonMouseClicked(evt);
            }
        });
        SearchReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchReservationButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchReservationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 140, 50));

        HistoryButton.setBackground(new java.awt.Color(204, 204, 204));
        HistoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HistoryButton.setForeground(new java.awt.Color(0, 0, 0));
        HistoryButton.setText("Room History");
        HistoryButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        HistoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HistoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryButtonMouseClicked(evt);
            }
        });
        HistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 140, 50));

        CheckOutButton.setBackground(new java.awt.Color(204, 204, 204));
        CheckOutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckOutButton.setForeground(new java.awt.Color(0, 0, 0));
        CheckOutButton.setText("Check Out");
        CheckOutButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CheckOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckOutButtonMouseClicked(evt);
            }
        });
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CheckOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 140, 50));

        backToGraphVisualizer.setBackground(new java.awt.Color(204, 204, 204));
        backToGraphVisualizer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backToGraphVisualizer.setForeground(new java.awt.Color(0, 0, 0));
        backToGraphVisualizer.setText("Visualize Graph");
        backToGraphVisualizer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        backToGraphVisualizer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToGraphVisualizer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToGraphVisualizerMouseClicked(evt);
            }
        });
        backToGraphVisualizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToGraphVisualizerActionPerformed(evt);
            }
        });
        jPanel1.add(backToGraphVisualizer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 220, 60));

        deleteUserInput.setBackground(new java.awt.Color(255, 255, 223));
        deleteUserInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteUserInput.setForeground(new java.awt.Color(153, 153, 153));
        deleteUserInput.setText("Room number | Example 12");
        deleteUserInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserInputMouseClicked(evt);
            }
        });
        deleteUserInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserInputActionPerformed(evt);
            }
        });
        jPanel1.add(deleteUserInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 380, 30));

        addUserInput.setBackground(new java.awt.Color(255, 255, 223));
        addUserInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addUserInput.setForeground(new java.awt.Color(153, 153, 153));
        addUserInput.setText("Last name, Name | Example Carreño, Luis");
        addUserInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserInputMouseClicked(evt);
            }
        });
        addUserInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserInputActionPerformed(evt);
            }
        });
        jPanel1.add(addUserInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 380, 30));

        deleteRelationInput.setBackground(new java.awt.Color(255, 255, 223));
        deleteRelationInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteRelationInput.setForeground(new java.awt.Color(153, 153, 153));
        deleteRelationInput.setText("ID | Example 29100210");
        deleteRelationInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteRelationInputMouseClicked(evt);
            }
        });
        deleteRelationInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRelationInputActionPerformed(evt);
            }
        });
        jPanel1.add(deleteRelationInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 380, 30));

        addRelationInput.setBackground(new java.awt.Color(255, 255, 223));
        addRelationInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addRelationInput.setForeground(new java.awt.Color(153, 153, 153));
        addRelationInput.setText("ID | Example 29100210");
        addRelationInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRelationInputMouseClicked(evt);
            }
        });
        addRelationInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRelationInputActionPerformed(evt);
            }
        });
        jPanel1.add(addRelationInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 380, 30));

        CheckInButton.setBackground(new java.awt.Color(204, 204, 204));
        CheckInButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckInButton.setForeground(new java.awt.Color(0, 0, 0));
        CheckInButton.setText("Check In");
        CheckInButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CheckInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckInButtonMouseClicked(evt);
            }
        });
        CheckInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CheckInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 140, 50));

        deleteRelationInput1.setBackground(new java.awt.Color(255, 255, 223));
        deleteRelationInput1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteRelationInput1.setForeground(new java.awt.Color(153, 153, 153));
        deleteRelationInput1.setText("ID | Example 29100210");
        deleteRelationInput1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteRelationInput1MouseClicked(evt);
            }
        });
        deleteRelationInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRelationInput1ActionPerformed(evt);
            }
        });
        jPanel1.add(deleteRelationInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 380, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckRegistrationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckRegistrationButtonMouseClicked

    }//GEN-LAST:event_CheckRegistrationButtonMouseClicked

    private void CheckRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckRegistrationButtonActionPerformed

    }//GEN-LAST:event_CheckRegistrationButtonActionPerformed

    private void SearchReservationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchReservationButtonMouseClicked
       
    }//GEN-LAST:event_SearchReservationButtonMouseClicked

    private void SearchReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchReservationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchReservationButtonActionPerformed

    private void HistoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryButtonMouseClicked
       
    }//GEN-LAST:event_HistoryButtonMouseClicked

    private void HistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryButtonActionPerformed

    private void CheckOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckOutButtonMouseClicked
       
    }//GEN-LAST:event_CheckOutButtonMouseClicked

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckOutButtonActionPerformed

    private void backToGraphVisualizerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToGraphVisualizerMouseClicked
       
    }//GEN-LAST:event_backToGraphVisualizerMouseClicked

    private void backToGraphVisualizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToGraphVisualizerActionPerformed

    }//GEN-LAST:event_backToGraphVisualizerActionPerformed

    private void deleteUserInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserInputMouseClicked
        
    }//GEN-LAST:event_deleteUserInputMouseClicked

    private void addUserInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserInputMouseClicked
        
    }//GEN-LAST:event_addUserInputMouseClicked

    private void addUserInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserInputActionPerformed

    private void deleteRelationInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteRelationInputMouseClicked
       
    }//GEN-LAST:event_deleteRelationInputMouseClicked

    private void deleteRelationInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRelationInputActionPerformed

    }//GEN-LAST:event_deleteRelationInputActionPerformed

    private void addRelationInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRelationInputMouseClicked
       
    }//GEN-LAST:event_addRelationInputMouseClicked

    private void addRelationInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRelationInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRelationInputActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void deleteUserInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserInputActionPerformed

    private void CheckInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckInButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckInButtonMouseClicked

    private void CheckInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckInButtonActionPerformed

    private void deleteRelationInput1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteRelationInput1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteRelationInput1MouseClicked

    private void deleteRelationInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRelationInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteRelationInput1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminActions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminActions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckInButton;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JButton CheckRegistrationButton;
    private javax.swing.JButton HistoryButton;
    private javax.swing.JButton SearchReservationButton;
    private javax.swing.JTextField addRelationInput;
    private javax.swing.JTextField addUserInput;
    private javax.swing.JButton backToGraphVisualizer;
    private javax.swing.JTextField deleteRelationInput;
    private javax.swing.JTextField deleteRelationInput1;
    private javax.swing.JTextField deleteUserInput;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
