/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author carre
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        cosmeticItem = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        welcomingText = new javax.swing.JTextArea();
        importFileButton = new javax.swing.JButton();
        continueWithoutImportingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, -1));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cosmeticItem.setBackground(new java.awt.Color(0, 200, 0));

        javax.swing.GroupLayout cosmeticItemLayout = new javax.swing.GroupLayout(cosmeticItem);
        cosmeticItem.setLayout(cosmeticItemLayout);
        cosmeticItemLayout.setHorizontalGroup(
            cosmeticItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        cosmeticItemLayout.setVerticalGroup(
            cosmeticItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        background.add(cosmeticItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 270, 590));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Welcome to the Hotel Admin Software");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 840, 50));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        welcomingText.setBackground(new java.awt.Color(204, 204, 204));
        welcomingText.setColumns(20);
        welcomingText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        welcomingText.setForeground(new java.awt.Color(0, 0, 0));
        welcomingText.setRows(5);
        welcomingText.setText("  To start, you have the posibility of choosing a csv\n\n  You can as well just work with the data that is already in the program!");
        welcomingText.setBorder(new javax.swing.border.MatteBorder(null));
        welcomingText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(welcomingText);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 640, 140));

        importFileButton.setBackground(new java.awt.Color(204, 204, 204));
        importFileButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        importFileButton.setForeground(new java.awt.Color(0, 0, 0));
        importFileButton.setText("Import File");
        importFileButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        importFileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        importFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importFileButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                importFileButtonMousePressed(evt);
            }
        });
        importFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importFileButtonActionPerformed(evt);
            }
        });
        background.add(importFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 170, 50));

        continueWithoutImportingButton.setBackground(new java.awt.Color(204, 204, 204));
        continueWithoutImportingButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        continueWithoutImportingButton.setForeground(new java.awt.Color(0, 0, 0));
        continueWithoutImportingButton.setText("Use current data");
        continueWithoutImportingButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        continueWithoutImportingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueWithoutImportingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueWithoutImportingButtonMouseClicked(evt);
            }
        });
        continueWithoutImportingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueWithoutImportingButtonActionPerformed(evt);
            }
        });
        background.add(continueWithoutImportingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 170, 50));

        jPanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importFileButtonMouseClicked

    }//GEN-LAST:event_importFileButtonMouseClicked

    private void importFileButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importFileButtonMousePressed

    }//GEN-LAST:event_importFileButtonMousePressed

    private void importFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importFileButtonActionPerformed
        
    }//GEN-LAST:event_importFileButtonActionPerformed

    private void continueWithoutImportingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueWithoutImportingButtonMouseClicked

    }//GEN-LAST:event_continueWithoutImportingButtonMouseClicked

    private void continueWithoutImportingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueWithoutImportingButtonActionPerformed

    }//GEN-LAST:event_continueWithoutImportingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton continueWithoutImportingButton;
    private javax.swing.JPanel cosmeticItem;
    private javax.swing.JButton importFileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea welcomingText;
    // End of variables declaration//GEN-END:variables
}
